[server]
maxUploadSize = 5
enableStaticServing = true

[deploy]
pythonVersion = "3.11"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
toolbarMode = "viewer"

[theme]
primaryColor = "#1a73e8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#222222"
font = "sans serif"
